### ISSUE TITLE
Check for sufficient lower bounds

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-game-servers#62]
```
>>> from google.cloud import gaming_v1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/google/cloud/gaming_v1/__init__.py", line 18, in <module>
    from .services.game_server_clusters_service import GameServerClustersServiceClient
  File "/usr/local/lib/python3.7/site-packages/google/cloud/gaming_v1/services/game_server_clusters_service/__init__.py", line 18, in <module>
    from .client import GameServerClustersServiceClient
  File "/usr/local/lib/python3.7/site-packages/google/cloud/gaming_v1/services/game_server_clusters_service/client.py", line 35, in <module>
    from google.cloud.gaming_v1.services.game_server_clusters_service import pagers
  File "/usr/local/lib/python3.7/site-packages/google/cloud/gaming_v1/services/game_server_clusters_service/pagers.py", line 20, in <module>
    from google.cloud.gaming_v1.types import game_server_clusters
  File "/usr/local/lib/python3.7/site-packages/google/cloud/gaming_v1/types/__init__.py", line 18, in <module>
    from .common import (
  File "/usr/local/lib/python3.7/site-packages/google/cloud/gaming_v1/types/common.py", line 41, in <module>
    class OperationMetadata(proto.Message):
  File "/usr/local/lib/python3.7/site-packages/proto/message.py", line 96, in __new__
    map_fields[msg_name] = MessageMeta(msg_name, (Message,), entry_attrs)
  File "/usr/local/lib/python3.7/site-packages/proto/message.py", line 217, in __new__
    field=[i.descriptor for i in fields],
  File "/usr/local/lib/python3.7/site-packages/proto/message.py", line 217, in <listcomp>
    field=[i.descriptor for i in fields],
  File "/usr/local/lib/python3.7/site-packages/proto/fields.py", line 113, in descriptor
    proto3_optional=self.optional,
ValueError: Protocol message FieldDescriptorProto has no "proto3_optional" field.
```

Customer using this library ended up with a `protobuf` version that was too old. Verify that lower bounds are pinned correctly here and in `google-api-core`.

**Comment by busunkim96** [comment]
This has been taken care of with the constraints file: https://github.com/googleapis/python-game-servers/blob/master/testing/constraints-3.6.txt
